from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class Nikki_dailyAssets: 


	# Click Rule Assets
	# 回家入口点击区域 
	C_BACK_HOME_ENTRANCE = RuleClick(roi_front=(501,1139,74,91), roi_back=(501,1139,74,91), name="back_home_entrance")
	# 暖暖手账打开后的无效区域 
	C_BACK_HOME_NOTEBOOK_INVALID_AREA = RuleClick(roi_front=(184,4,173,47), roi_back=(184,4,173,47), name="back_home_notebook_invalid_area")
	# 日常采购中小物-电影票的点击区域 
	C_BACK_HOME_PURCHASE_MOVIE = RuleClick(roi_front=(86,602,133,139), roi_back=(86,602,133,139), name="back_home_purchase_movie")
	# 日常采购中小物-缤纷调色盘的点击区域 
	C_BACK_HOME_PURCHASE_DRAW = RuleClick(roi_front=(507,601,133,139), roi_back=(507,601,133,139), name="back_home_purchase_draw")
	# 日常采购中小物-晴雨伞的点击区域 
	C_BACK_HOME_PURCHASE_UMBRELLA = RuleClick(roi_front=(285,827,152,66), roi_back=(285,827,152,66), name="back_home_purchase_umbrella")
	# 日常采购零食栏点击区域 
	C_BACK_HOME_PURCHASE_TAB_SNACK = RuleClick(roi_front=(377,281,90,37), roi_back=(377,281,90,37), name="back_home_purchase_tab_snack")
	# 日常采购中零食-薯片的点击区域 
	C_BACK_HOME_PURCHASE_SNACK_CHIPS = RuleClick(roi_front=(86,602,133,139), roi_back=(86,602,133,139), name="back_home_purchase_snack_chips")


	# Image Rule Assets
	# 回家页面 
	I_BACK_HOME_PAGE = RuleImage(roi_front=(20,170,34,35), roi_back=(20,170,34,35), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/back_home/back_home_page.png")
	# 进入回家界面后，提示活力值满去采购的框的取消按钮 
	I_BACK_HOME_CANCEL_TIP = RuleImage(roi_front=(143,684,166,57), roi_back=(143,684,166,57), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/back_home/back_home_cancel_tip.png")
	# 暖暖手账图标 
	I_BACK_HOME_NOTEBOOK = RuleImage(roi_front=(642,600,41,59), roi_back=(642,600,41,59), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/back_home/back_home_notebook.png")
	# 暖暖手账打开按钮图标 
	I_BACK_HOME_NOTEBOOK_OPEN = RuleImage(roi_front=(539,592,153,64), roi_back=(539,592,153,64), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/back_home/back_home_notebook_open.png")
	# 日常采购图标 
	I_BACK_HOME_PURCHASE = RuleImage(roi_front=(640,500,42,60), roi_back=(640,500,42,60), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/back_home/back_home_purchase.png")
	# 采购下的购买图标 
	I_BACK_HOME_PURCHASE_BUY = RuleImage(roi_front=(542,957,92,55), roi_back=(542,957,92,55), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/back_home/back_home_purchase_buy.png")
	# 日常采购零食栏选中状态 
	I_BACK_HOME_PURCHASE_SNACK_CHECKED = RuleImage(roi_front=(377,281,90,37), roi_back=(377,281,90,37), threshold=0.99, method="Template matching", file="./tasks/Nikki_daily/back_home/back_home_purchase_snack_checked.png")


	# Ocr Rule Assets
	# 主页回家文本 
	O_BACK_HOME_ENTRANCE_TEXT = RuleOcr(roi=(519,1205,42,24), area=(519,1205,42,24), mode="Single", method="Default", keyword="回家", name="back_home_entrance_text")
	# 日常采购购买图标上价格显示 
	O_BACK_HOME_PURCHASE_PRICE = RuleOcr(roi=(482,969,66,35), area=(482,969,66,35), mode="Digit", method="Default", keyword="", name="back_home_purchase_price")


	# Click Rule Assets
	# 点赞按钮区域 
	C_COLLOCATION_ARENA_LIKE_1 = RuleClick(roi_front=(135,1063,86,84), roi_back=(135,1063,86,84), name="collocation_arena_like_1")
	# 点赞按钮区域 
	C_COLLOCATION_ARENA_LIKE_2 = RuleClick(roi_front=(501,1063,86,84), roi_back=(501,1063,86,84), name="collocation_arena_like_2")


	# Image Rule Assets
	# 搭配评选赛入口图标 
	I_COLLOCATION_ARENA_ENTRANCE = RuleImage(roi_front=(29,409,95,138), roi_back=(29,409,95,138), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/collocation_arena/collocation_arena_entrance.png")
	# 搭配评选赛页面 
	I_COLLOCATION_ARENA_PAGE = RuleImage(roi_front=(29,1167,102,69), roi_back=(29,1167,102,69), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/collocation_arena/collocation_arena_page.png")
	# 我当评委按钮 
	I_COLLOCATION_ARENA_BUTTON = RuleImage(roi_front=(574,1167,95,68), roi_back=(574,1167,95,68), threshold=0.6, method="Template matching", file="./tasks/Nikki_daily/collocation_arena/collocation_arena_button.png")
	# 搭配评选赛vs图标 
	I_COLLOCATION_ARENA_VS = RuleImage(roi_front=(315,1084,91,63), roi_back=(315,1084,91,63), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/collocation_arena/collocation_arena_vs.png")


	# Click Rule Assets
	# 快速组队按钮点击区域 
	C_COMPANION_TASK_QUICK_BUTTON = RuleClick(roi_front=(527,1140,137,49), roi_back=(527,1140,137,49), name="companion_task_quick_button")
	# +按钮点击区域 
	C_COMPANION_TASK_ADD_BUTTON = RuleClick(roi_front=(635,1077,33,29), roi_back=(635,1077,33,29), name="companion_task_add_button")
	# -按钮点击区域 
	C_COMPANION_TASK_REDUCE_BUTTON = RuleClick(roi_front=(519,1077,33,29), roi_back=(519,1077,33,29), name="companion_task_reduce_button")
	# 不落的帷幕选择区域 
	C_COMPANION_TASK_CURTAIN_AREA_1 = RuleClick(roi_front=(127,173,494,151), roi_back=(127,173,494,151), name="companion_task_curtain_area_1")
	# 不落的帷幕选择区域 
	C_COMPANION_TASK_CURTAIN_AREA_2 = RuleClick(roi_front=(127,378,494,151), roi_back=(127,378,494,151), name="companion_task_curtain_area_2")
	# 不落的帷幕选择区域 
	C_COMPANION_TASK_CURTAIN_AREA_3 = RuleClick(roi_front=(127,585,494,151), roi_back=(127,585,494,151), name="companion_task_curtain_area_3")
	# 不落的帷幕选择区域 
	C_COMPANION_TASK_CURTAIN_AREA_4 = RuleClick(roi_front=(127,793,494,151), roi_back=(127,793,494,151), name="companion_task_curtain_area_4")
	# 不落的帷幕选择区域 
	C_COMPANION_TASK_CURTAIN_AREA_5 = RuleClick(roi_front=(127,1001,494,151), roi_back=(127,1001,494,151), name="companion_task_curtain_area_5")


	# Image Rule Assets
	# 结伴tab未被选中 
	I_COMPANION_TASK_TAB_UNCHECKED = RuleImage(roi_front=(443,1158,95,71), roi_back=(443,1158,95,71), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/companion_task/companion_task_tab_unchecked.png")
	# 结伴tab被选中 
	I_COMPANION_TASK_TAB_CHECKED = RuleImage(roi_front=(443,1158,95,71), roi_back=(443,1158,95,71), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/companion_task/companion_task_tab_checked.png")
	# 时光钟表铺 
	I_COMPANION_TASK_TIME = RuleImage(roi_front=(197,338,148,52), roi_back=(197,338,148,52), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/companion_task/companion_task_time.png")
	# 时光钟表铺难度unchecked 
	I_COMPANION_TASK_TIME_LEVEL_UNCHECKED = RuleImage(roi_front=(551,738,89,87), roi_back=(551,738,89,87), threshold=0.9, method="Template matching", file="./tasks/Nikki_daily/companion_task/companion_task_time_level_unchecked.png")
	# 时光钟表铺难度checked 
	I_COMPANION_TASK_TIME_LEVEL_CHECKED = RuleImage(roi_front=(551,738,89,87), roi_back=(551,738,89,87), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/companion_task/companion_task_time_level_checked.png")
	# 不落的帷幕 
	I_COMPANION_TASK_CURTAIN = RuleImage(roi_front=(343,525,148,52), roi_back=(343,525,148,52), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/companion_task/companion_task_curtain.png")
	# 不落的帷幕选择界面 
	I_COMPANION_TASK_CURTAIN_PAGE = RuleImage(roi_front=(382,85,278,52), roi_back=(382,85,278,52), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/companion_task/companion_task_curtain_page.png")
	# 不落的帷幕难度checked 
	I_COMPANION_TASK_CURTAIN_LEVEL_CHECKED = RuleImage(roi_front=(569,744,84,64), roi_back=(569,744,84,64), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/companion_task/companion_task_curtain_level_checked.png")
	# 不落的帷幕难度unchecked 
	I_COMPANION_TASK_CURTAIN_LEVEL_UNCHECKED = RuleImage(roi_front=(569,744,84,64), roi_back=(569,744,84,64), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/companion_task/companion_task_curtain_level_unchecked.png")
	# 印象旅航 
	I_COMPANION_TASK_TRAVEL = RuleImage(roi_front=(328,751,148,52), roi_back=(328,751,148,52), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/companion_task/companion_task_travel.png")
	# 印象旅航难度checked 
	I_COMPANION_TASK_TRAVEL_LEVEL_CHECKED = RuleImage(roi_front=(556,755,81,81), roi_back=(556,755,81,81), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/companion_task/companion_task_travel_level_checked.png")
	# 印象旅航难度unchecked 
	I_COMPANION_TASK_TRAVEL_LEVEL_UNCHECKED = RuleImage(roi_front=(556,755,81,81), roi_back=(556,755,81,81), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/companion_task/companion_task_travel_level_unchecked.png")
	# 独自登场按钮 
	I_COMPANION_TASK_ALONE_BUTTON = RuleImage(roi_front=(55,1139,143,48), roi_back=(55,1139,143,48), threshold=0.9, method="Template matching", file="./tasks/Nikki_daily/companion_task/companion_task_alone_button.png")
	# tab难度checked 
	I_COMPANION_TASK_TAB_LEVEL_CHECKED = RuleImage(roi_front=(380,694,115,48), roi_back=(380,694,115,48), threshold=0.6, method="Template matching", file="./tasks/Nikki_daily/companion_task/companion_task_tab_level_checked.png")
	# tab难度checked 
	I_COMPANION_TASK_TAB_LEVEL_UNCHECKED = RuleImage(roi_front=(380,694,115,48), roi_back=(380,694,115,48), threshold=0.6, method="Template matching", file="./tasks/Nikki_daily/companion_task/companion_task_tab_level_unchecked.png")


	# Ocr Rule Assets
	# 快速组队次数 
	O_COMPANION_TASK_NUM = RuleOcr(roi=(583,1080,19,22), area=(583,1080,19,22), mode="Digit", method="Default", keyword="", name="companion_task_num")


	# Click Rule Assets
	# 切换章节/期数按钮点击区域 
	C_CORRIDOR_TASK_EXCHANGE_BUTTON = RuleClick(roi_front=(593,186,124,38), roi_back=(593,186,124,38), name="corridor_task_exchange_button")
	# 切换期数弹窗第一期的点击区域 
	C_CORRIDOR_TASK_FIRST_ISSUE = RuleClick(roi_front=(89,302,523,171), roi_back=(89,302,523,171), name="corridor_task_first_issue")
	# 分享后点击返回区域回游戏 
	C_CORRIDOR_TASK_BACK_GAME = RuleClick(roi_front=(4,60,75,62), roi_back=(4,60,75,62), name="corridor_task_back_game")
	# 期数列表中期数点击区域 
	C_CORRIDOR_TASK_POP_CLICK_1 = RuleClick(roi_front=(87,399,533,180), roi_back=(87,399,533,180), name="corridor_task_pop_click_1")
	# 期数列表中期数点击区域 
	C_CORRIDOR_TASK_POP_CLICK_2 = RuleClick(roi_front=(87,638,533,180), roi_back=(87,638,533,180), name="corridor_task_pop_click_2")
	# 期数列表中期数点击区域 
	C_CORRIDOR_TASK_POP_CLICK_3 = RuleClick(roi_front=(87,877,533,180), roi_back=(87,877,533,180), name="corridor_task_pop_click_3")
	# 期数列表中期数点击区域 
	C_CORRIDOR_TASK_POP_CLICK_4 = RuleClick(roi_front=(87,282,533,66), roi_back=(87,282,533,66), name="corridor_task_pop_click_4")
	# 第五六期，制作服装点击区域 
	C_CORRIDOR_TASK_CLICK_1 = RuleClick(roi_front=(272,1029,174,130), roi_back=(272,1029,174,130), name="corridor_task_click_1")
	# 第四期，制作服装点击区域 
	C_CORRIDOR_TASK_CLICK_2 = RuleClick(roi_front=(452,1122,225,77), roi_back=(452,1122,225,77), name="corridor_task_click_2")
	# 第七期，制作服装点击区域 
	C_CORRIDOR_TASK_CLICK_3 = RuleClick(roi_front=(41,1057,204,117), roi_back=(41,1057,204,117), name="corridor_task_click_3")
	# 套装制作点击区域 
	C_CORRIDOR_TASK_MAKE_TAB_CLICK = RuleClick(roi_front=(575,505,93,89), roi_back=(575,505,93,89), name="corridor_task_make_tab_click")
	# 影之唤醒点击区域 
	C_CORRIDOR_TASK_WAKE_TAB_CLICK = RuleClick(roi_front=(392,949,113,106), roi_back=(392,949,113,106), name="corridor_task_wake_tab_click")


	# Image Rule Assets
	# 时空回廊入口图标 
	I_CORRIDOR_TASK_ENTRANCE = RuleImage(roi_front=(316,837,143,76), roi_back=(316,837,143,76), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/corridor_task/corridor_task_entrance.png")
	# 切换章节 
	I_CORRIDOR_TASK_EXCHANGE_1 = RuleImage(roi_front=(593,186,124,38), roi_back=(593,186,124,38), threshold=0.7, method="Template matching", file="./tasks/Nikki_daily/corridor_task/corridor_task_exchange_1.png")
	# 切换期数 
	I_CORRIDOR_TASK_EXCHANGE_2 = RuleImage(roi_front=(593,186,124,38), roi_back=(593,186,124,38), threshold=0.7, method="Template matching", file="./tasks/Nikki_daily/corridor_task/corridor_task_exchange_2.png")
	# 切换期数弹窗标题 
	I_CORRIDOR_TASK_POP_PAGE = RuleImage(roi_front=(283,202,154,41), roi_back=(283,202,154,41), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/corridor_task/corridor_task_pop_page.png")
	# 第一期分享按钮 
	I_CORRIDOR_TASK_SHARE_BUTTON = RuleImage(roi_front=(44,799,50,46), roi_back=(44,799,50,46), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/corridor_task/corridor_task_share_button.png")
	# 分享微信按钮 
	I_CORRIDOR_TASK_SHARE_WEIXIN = RuleImage(roi_front=(201,1195,46,42), roi_back=(201,1195,46,42), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/corridor_task/corridor_task_share_weixin.png")
	# 套装制作tab选中状态 
	I_CORRIDOR_TASK_MAKE_TAB_CHECKED = RuleImage(roi_front=(214,109,132,42), roi_back=(214,109,132,42), threshold=0.9, method="Template matching", file="./tasks/Nikki_daily/corridor_task/corridor_task_make_tab_checked.png")
	# 影之唤醒tab选中状态 
	I_CORRIDOR_TASK_WAKE_TAB_CHECKED = RuleImage(roi_front=(382,107,129,44), roi_back=(382,107,129,44), threshold=0.9, method="Template matching", file="./tasks/Nikki_daily/corridor_task/corridor_task_wake_tab_checked.png")


	# Ocr Rule Assets
	# 期数列表中识别期数信息 
	O_CORRIDOR_TASK_POP_TEXT_1 = RuleOcr(roi=(555,426,71,25), area=(555,426,71,25), mode="Single", method="Default", keyword="", name="corridor_task_pop_text_1")
	# 期数列表中识别期数信息 
	O_CORRIDOR_TASK_POP_TEXT_2 = RuleOcr(roi=(555,662,71,25), area=(555,662,71,25), mode="Single", method="Default", keyword="", name="corridor_task_pop_text_2")
	# 期数列表中识别期数信息 
	O_CORRIDOR_TASK_POP_TEXT_3 = RuleOcr(roi=(555,898,71,25), area=(555,898,71,25), mode="Single", method="Default", keyword="", name="corridor_task_pop_text_3")
	# 拉到底部时，识别倒数第四个期数名称 
	O_CORRIDOR_TASK_POP_TEXT_4 = RuleOcr(roi=(479,281,113,33), area=(479,281,113,33), mode="Single", method="Default", keyword="", name="corridor_task_pop_text_4")


	# Swipe Rule Assets
	# 向上滑动tab内容 
	S_CORRIDOR_TASK_SWIPE = RuleSwipe(roi_front=(98,972,517,63), roi_back=(98,275,517,63), mode="default", name="corridor_task_swipe")


	# Click Rule Assets
	# 任务中礼盒点击区域 
	C_DAILY_REWARD_PACKAGE = RuleClick(roi_front=(629,526,66,42), roi_back=(629,526,66,42), name="daily_reward_package")
	# 时尚任务tab的点击区域 
	C_DAILY_REWARD_FASHION_TAB = RuleClick(roi_front=(439,639,200,44), roi_back=(439,639,200,44), name="daily_reward_fashion_tab")


	# Image Rule Assets
	# 任务主页入口图标 
	I_DAILY_REWARD_ENTRANCE = RuleImage(roi_front=(653,831,35,37), roi_back=(653,831,35,37), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/daily_reward/daily_reward_entrance.png")
	# 任务-今日日程tab选中状态 
	I_DAILY_REWARD_TODAY_TAB_CHECKED = RuleImage(roi_front=(54,115,123,43), roi_back=(54,115,123,43), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/daily_reward/daily_reward_today_tab_checked.png")
	# 任务-一键领取按钮 
	I_DAILY_REWARD_ONE_CLICK = RuleImage(roi_front=(284,1208,151,51), roi_back=(284,1208,151,51), threshold=0.9, method="Template matching", file="./tasks/Nikki_daily/daily_reward/daily_reward_one_click.png")
	# 任务中奖励被领取后的图标 
	I_DAILY_REWARD_PACKAGE_OPEN = RuleImage(roi_front=(629,526,66,42), roi_back=(629,526,66,42), threshold=0.9, method="Template matching", file="./tasks/Nikki_daily/daily_reward/daily_reward_package_open.png")
	# 时尚任务任务提示 
	I_DAILY_REWARD_FASHION_TIP = RuleImage(roi_front=(648,621,21,21), roi_back=(648,621,21,21), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/daily_reward/daily_reward_fashion_tip.png")
	# 时尚任务tab的选中状态 
	I_DAILY_REWARD_FASHION_TAB_CHECKED = RuleImage(roi_front=(439,639,200,44), roi_back=(439,639,200,44), threshold=0.9, method="Template matching", file="./tasks/Nikki_daily/daily_reward/daily_reward_fashion_tab_checked.png")


	# Click Rule Assets
	# 快速挑战点击区域 
	C_DIAMOND_ARENA_SKIP = RuleClick(roi_front=(562,516,23,20), roi_back=(562,516,23,20), name="diamond_arena_skip")
	# 换一批按钮点击区域 
	C_DIAMOND_ARENA_CHANGE = RuleClick(roi_front=(157,1109,86,36), roi_back=(157,1109,86,36), name="diamond_arena_change")
	# 挑战点击区域 
	C_DIAMOND_ARENA_CHALLENGE_1 = RuleClick(roi_front=(38,823,167,100), roi_back=(38,823,167,100), name="diamond_arena_challenge_1")
	# 挑战点击区域 
	C_DIAMOND_ARENA_CHALLENGE_2 = RuleClick(roi_front=(276,823,167,100), roi_back=(276,823,167,100), name="diamond_arena_challenge_2")
	# 挑战点击区域 
	C_DIAMOND_ARENA_CHALLENGE_3 = RuleClick(roi_front=(514,823,167,100), roi_back=(514,823,167,100), name="diamond_arena_challenge_3")


	# Image Rule Assets
	# 钻石竞技场入口图标 
	I_DIAMOND_ARENA_ENTRANCE = RuleImage(roi_front=(399,638,143,76), roi_back=(399,638,143,76), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/diamond_arena/diamond_arena_entrance.png")
	# 新赛季开始确认按钮 
	I_DIAMOND_ARENA_SEASON = RuleImage(roi_front=(270,922,176,60), roi_back=(270,922,176,60), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/diamond_arena/diamond_arena_season.png")
	# 新一周开始确认按钮 
	I_DIAMOND_ARENA_WEEK = RuleImage(roi_front=(214,910,291,51), roi_back=(214,910,291,51), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/diamond_arena/diamond_arena_week.png")
	# 我的搭配按钮 
	I_DIAMOND_ARENA_COLLOCATION = RuleImage(roi_front=(502,576,160,59), roi_back=(502,576,160,59), threshold=0.99, method="Template matching", file="./tasks/Nikki_daily/diamond_arena/diamond_arena_collocation.png")
	# 闪耀之阶按钮 
	I_DIAMOND_ARENA_RANKED = RuleImage(roi_front=(590,188,125,53), roi_back=(590,188,125,53), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/diamond_arena/diamond_arena_ranked.png")
	# 快速挑战勾选状态 
	I_DIAMOND_ARENA_SKIP_CHECKED = RuleImage(roi_front=(562,516,23,20), roi_back=(562,516,23,20), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/diamond_arena/diamond_arena_skip_checked.png")
	# 挑战后结果弹窗 
	I_DIAMOND_ARENA_CHALLENGE_PAGE = RuleImage(roi_front=(299,239,126,49), roi_back=(299,239,126,49), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/diamond_arena/diamond_arena_challenge_page.png")
	# 对方玩家名次变化确认按钮 
	I_DIAMOND_ARENA_OTHER_SURE = RuleImage(roi_front=(282,684,158,57), roi_back=(282,684,158,57), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/diamond_arena/diamond_arena_other_sure.png")


	# Ocr Rule Assets
	# 我的竞技场战力数据 
	O_DIAMOND_ARENA_NUM = RuleOcr(roi=(352,677,83,23), area=(352,677,83,23), mode="Digit", method="Default", keyword="", name="diamond_arena_num")
	# 挑战剩余次数 
	O_DIAMOND_ARENA_REMAIN = RuleOcr(roi=(597,1103,56,25), area=(597,1103,56,25), mode="DigitCounter", method="Default", keyword="", name="diamond_arena_remain")
	# 他人战力 
	O_DIAMOND_ARENA_OTHER_NUM_1 = RuleOcr(roi=(132,1050,90,22), area=(132,1050,90,22), mode="Digit", method="Default", keyword="", name="diamond_arena_other_num_1")
	# 他人战力 
	O_DIAMOND_ARENA_OTHER_NUM_2 = RuleOcr(roi=(372,1050,90,22), area=(372,1050,90,22), mode="Digit", method="Default", keyword="", name="diamond_arena_other_num_2")
	# 他人战力 
	O_DIAMOND_ARENA_OTHER_NUM_3 = RuleOcr(roi=(612,1050,90,22), area=(612,1050,90,22), mode="Digit", method="Default", keyword="", name="diamond_arena_other_num_3")


	# Click Rule Assets
	# 制衣引导入口点击区域 
	C_EXPEND_POWER_ENTRANCE = RuleClick(roi_front=(423,95,226,109), roi_back=(423,95,226,109), name="expend_power_entrance")
	# 制衣目标点击区域 
	C_EXPEND_POWER_TARGET_CLICK_1 = RuleClick(roi_front=(45,753,251,316), roi_back=(45,753,251,316), name="expend_power_target_click_1")
	# 制衣目标点击区域 
	C_EXPEND_POWER_TARGET_CLICK_2 = RuleClick(roi_front=(360,753,251,316), roi_back=(360,753,251,316), name="expend_power_target_click_2")
	# 稀有-套装制作-材料点击区域 
	C_EXPEND_POWER_RARE_MAKE_1 = RuleClick(roi_front=(583,511,84,75), roi_back=(583,511,84,75), name="expend_power_rare_make_1")
	# 稀有-套装制作-材料点击区域 
	C_EXPEND_POWER_RARE_MAKE_2 = RuleClick(roi_front=(583,668,84,75), roi_back=(583,668,84,75), name="expend_power_rare_make_2")
	# 稀有-影之召唤-材料点击区域 
	C_EXPEND_POWER_RARE_WAKE_1 = RuleClick(roi_front=(71,956,116,93), roi_back=(71,956,116,93), name="expend_power_rare_wake_1")
	# 稀有-影之召唤-材料点击区域 
	C_EXPEND_POWER_RARE_WAKE_2 = RuleClick(roi_front=(300,956,116,93), roi_back=(300,956,116,93), name="expend_power_rare_wake_2")
	# 稀有-影之召唤-材料点击区域 
	C_EXPEND_POWER_RARE_WAKE_3 = RuleClick(roi_front=(529,956,116,93), roi_back=(529,956,116,93), name="expend_power_rare_wake_3")
	# 闪耀-套装制作-材料点击区域 
	C_EXPEND_POWER_SHINE_MAKE = RuleClick(roi_front=(438,668,84,75), roi_back=(438,668,84,75), name="expend_power_shine_make")
	# 闪耀-影之召唤-材料点击区域 
	C_EXPEND_POWER_SHINE_WAKE_1 = RuleClick(roi_front=(43,956,116,93), roi_back=(43,956,116,93), name="expend_power_shine_wake_1")
	# 闪耀-影之召唤-材料点击区域 
	C_EXPEND_POWER_SHINE_WAKE_2 = RuleClick(roi_front=(215,956,116,93), roi_back=(215,956,116,93), name="expend_power_shine_wake_2")


	# Image Rule Assets
	# 制衣引导页面 
	I_EXPEND_POWER_PAGE = RuleImage(roi_front=(241,11,229,64), roi_back=(241,11,229,64), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/expend_power/expend_power_page.png")
	# 制衣目标存在图标 
	I_EXPEND_POWER_TARGET_1 = RuleImage(roi_front=(281,626,26,25), roi_back=(281,626,26,25), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/expend_power/expend_power_target.png")
	# 制衣目标存在图标 
	I_EXPEND_POWER_TARGET_2 = RuleImage(roi_front=(596,626,26,25), roi_back=(596,626,26,25), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/expend_power/expend_power_target.png")


	# Ocr Rule Assets
	# 制衣引导入口文本 
	O_EXPEND_POWER_ENTRANCE_TEXT = RuleOcr(roi=(479,173,102,25), area=(479,173,102,25), mode="Single", method="Default", keyword="制衣引导", name="expend_power_entrance_text")
	# 判断稀有度 
	O_EXPEND_POWER_RARITY = RuleOcr(roi=(602,90,106,71), area=(602,90,106,71), mode="Single", method="Default", keyword="", name="expend_power_rarity")
	# 判断稀有度2 
	O_EXPEND_POWER_RARITY2 = RuleOcr(roi=(602,179,106,71), area=(602,179,106,71), mode="Single", method="Default", keyword="", name="expend_power_rarity2")
	# 稀有-套装制作-材料数量 
	O_EXPEND_POWER_RARE_MAKE_1 = RuleOcr(roi=(629,482,64,22), area=(629,482,64,22), mode="DigitCounter", method="Default", keyword="", name="expend_power_rare_make_1")
	# 稀有-套装制作-材料数量 
	O_EXPEND_POWER_RARE_MAKE_2 = RuleOcr(roi=(629,639,55,22), area=(629,639,55,22), mode="DigitCounter", method="Default", keyword="", name="expend_power_rare_make_2")
	# 稀有-影之唤醒-材料数量 
	O_EXPEND_POWER_RARE_WAKE_1 = RuleOcr(roi=(149,922,65,23), area=(149,922,65,23), mode="DigitCounter", method="Default", keyword="", name="expend_power_rare_wake_1")
	# 稀有-影之唤醒-材料数量 
	O_EXPEND_POWER_RARE_WAKE_2 = RuleOcr(roi=(378,922,65,23), area=(378,922,65,23), mode="DigitCounter", method="Default", keyword="", name="expend_power_rare_wake_2")
	# 稀有-影之唤醒-材料数量 
	O_EXPEND_POWER_RARE_WAKE_3 = RuleOcr(roi=(607,922,65,23), area=(607,922,65,23), mode="DigitCounter", method="Default", keyword="", name="expend_power_rare_wake_3")
	# 闪耀-套装制作-材料数量 
	O_EXPEND_POWER_SHINE_MAKE = RuleOcr(roi=(486,639,64,22), area=(492,639,64,22), mode="DigitCounter", method="Default", keyword="", name="expend_power_shine_make")
	# 闪耀-影之唤醒-材料数量 
	O_EXPEND_POWER_SHINE_WAKE_1 = RuleOcr(roi=(105,922,95,26), area=(105,922,95,26), mode="DigitCounter", method="Default", keyword="", name="expend_power_shine_wake_1")
	# 闪耀-影之唤醒-材料数量 
	O_EXPEND_POWER_SHINE_WAKE_2 = RuleOcr(roi=(278,922,95,26), area=(278,922,95,26), mode="DigitCounter", method="Default", keyword="", name="expend_power_shine_wake_2")


	# Image Rule Assets
	# 好友主页入口图标 
	I_FRIEND_POWER_ENTRANCE = RuleImage(roi_front=(657,179,38,42), roi_back=(657,179,38,42), threshold=0.5, method="Template matching", file="./tasks/Nikki_daily/friend_power/friend_power_entrance.png")
	# 好友页面一键送心按钮 
	I_FRIEND_POWER_SEND_BUTTON = RuleImage(roi_front=(24,1197,152,53), roi_back=(24,1197,152,53), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/friend_power/friend_power_send_button.png")
	# 好友页面领取体力按钮 
	I_FRIEND_POWER_RECEIVE_BUTTON = RuleImage(roi_front=(213,1199,154,53), roi_back=(213,1199,154,53), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/friend_power/friend_power_receive_button.png")
	# 好友领取体力弹窗标题 
	I_FRIEND_POWER_RECEIVE_POP = RuleImage(roi_front=(296,257,130,34), roi_back=(296,257,130,34), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/friend_power/friend_power_receive_pop.png")
	# 好友一键领取体力按钮 
	I_FRIEND_POWER_ONE_CLICK_RECEIVE = RuleImage(roi_front=(221,950,268,49), roi_back=(221,950,268,49), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/friend_power/friend_power_one_click_receive.png")


	# Click Rule Assets
	# 心之门无效的点击区域 
	C_HEART_GATE_INVALID_AREA = RuleClick(roi_front=(28,1197,172,62), roi_back=(28,1197,172,62), name="heart_gate_invalid_area")
	# 心之门切换按钮 
	C_HEART_GATE_SWITCH = RuleClick(roi_front=(650,489,55,77), roi_back=(650,489,55,77), name="heart_gate_switch")


	# Image Rule Assets
	# 心之门主页入口图标 
	I_HEART_GATE_ENTRANCE_1 = RuleImage(roi_front=(33,493,44,38), roi_back=(33,493,44,38), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/heart_gate/heart_gate_entrance.png")
	# 心之门主页入口图标 
	I_HEART_GATE_ENTRANCE_2 = RuleImage(roi_front=(33,276,44,38), roi_back=(33,276,44,38), threshold=0.6, method="Template matching", file="./tasks/Nikki_daily/heart_gate/heart_gate_entrance.png")
	# 心之门主页入口图标 
	I_HEART_GATE_ENTRANCE_3 = RuleImage(roi_front=(33,378,44,38), roi_back=(33,378,44,38), threshold=0.6, method="Template matching", file="./tasks/Nikki_daily/heart_gate/heart_gate_entrance.png")
	# 心之门主页入口图标 
	I_HEART_GATE_ENTRANCE_4 = RuleImage(roi_front=(33,605,44,38), roi_back=(33,605,44,38), threshold=0.6, method="Template matching", file="./tasks/Nikki_daily/heart_gate/heart_gate_entrance.png")
	# 幻之海免费感应一次按钮 
	I_HEART_GATE_MAGICAL_INDUCE = RuleImage(roi_front=(78,1073,246,54), roi_back=(78,1073,246,54), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/heart_gate/heart_gate_magical_induce.png")
	# 谜之海感应一次按钮 
	I_HEART_GATE_PUZZLE_INDUCE = RuleImage(roi_front=(41,1074,172,57), roi_back=(41,1074,172,57), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/heart_gate/heart_gate_puzzle_induce.png")


	# Ocr Rule Assets
	# 进入心之门之后显示的感应详情 
	O_HEART_GATE_DETAIL = RuleOcr(roi=(593,70,104,32), area=(593,70,104,32), mode="Single", method="Default", keyword="感应详情", name="heart_gate_detail")
	# 幻之海图片文本 
	O_HEART_GATE_MAGICAL = RuleOcr(roi=(23,113,79,122), area=(23,113,79,122), mode="Single", method="Default", keyword="勾", name="heart_gate_magical")
	# 幻之海流光下期预告文本 
	O_HEART_GATE_NEXT = RuleOcr(roi=(615,162,76,22), area=(615,162,76,22), mode="Single", method="Default", keyword="下期预告", name="heart_gate_next")
	# 幻之海免费抽文本 
	O_HEART_GATE_MAGICAL_FREE = RuleOcr(roi=(92,1085,57,31), area=(92,1085,57,31), mode="Single", method="Default", keyword="免费", name="heart_gate_magical_free")
	# 谜之海图片文本 
	O_HEART_GATE_PUZZLE = RuleOcr(roi=(24,114,86,285), area=(24,114,86,285), mode="Single", method="Default", keyword="谜之海", name="heart_gate_puzzle")
	# 绮之券图片文本 
	O_HEART_GATE_QI = RuleOcr(roi=(599,1231,62,25), area=(599,1231,62,25), mode="Single", method="Default", keyword="绮之券", name="heart_gate_qi")


	# Click Rule Assets
	# 真我之境的点击区域 
	C_MEMORY_OCEAN_MAIN_TASK = RuleClick(roi_front=(403,604,88,89), roi_back=(403,604,88,89), name="memory_ocean_main_task")
	# 真我之境开始搭配点击区域 
	C_MEMORY_OCEAN_MAIN_TASK_COLLOCATION_1 = RuleClick(roi_front=(99,723,109,82), roi_back=(99,723,109,82), name="memory_ocean_main_task_collocation_1")
	# 真我之境开始搭配点击区域 
	C_MEMORY_OCEAN_MAIN_TASK_COLLOCATION_2 = RuleClick(roi_front=(303,723,109,82), roi_back=(303,723,109,82), name="memory_ocean_main_task_collocation_2")
	# 真我之境开始搭配点击区域 
	C_MEMORY_OCEAN_MAIN_TASK_COLLOCATION_3 = RuleClick(roi_front=(507,723,109,82), roi_back=(507,723,109,82), name="memory_ocean_main_task_collocation_3")
	# 忆海心阶真我之境弹窗跳过战斗点击区域 
	C_MEMORY_OCEAN_MAIN_TASK_SKIP = RuleClick(roi_front=(506,978,32,31), roi_back=(506,978,32,31), name="memory_ocean_main_task_skip")
	# 境遇1的点击区域 
	C_MEMORY_OCEAN_SUB_TASK_1 = RuleClick(roi_front=(165,703,81,64), roi_back=(165,703,81,64), name="memory_ocean_sub_task_1")
	# 境遇3的点击区域 
	C_MEMORY_OCEAN_SUB_TASK_2 = RuleClick(roi_front=(363,880,81,64), roi_back=(363,880,81,64), name="memory_ocean_sub_task_2")


	# Image Rule Assets
	# 忆海心阶入口图标 
	I_MEMORY_OCEAN_ENTRANCE = RuleImage(roi_front=(162,991,143,76), roi_back=(162,991,143,76), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/memory_ocean/memory_ocean_entrance.png")
	# 忆海心阶页面 
	I_MEMORY_OCEAN_PAGE = RuleImage(roi_front=(488,61,184,149), roi_back=(488,61,184,149), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/memory_ocean/memory_ocean_page.png")
	# 忆海心阶快速挑战按钮 
	I_MEMORY_OCEAN_QUICK_BUTTON = RuleImage(roi_front=(33,1125,108,28), roi_back=(33,1125,108,28), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/memory_ocean/memory_ocean_quick_button.png")
	# 忆海心阶真我之境弹窗页面标题 
	I_MEMORY_OCEAN_MAIN_TASK_PAGE = RuleImage(roi_front=(56,261,249,51), roi_back=(56,261,249,51), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/memory_ocean/memory_ocean_main_task_page.png")
	# 忆海心阶真我之境弹窗跳过战斗勾选 
	I_MEMORY_OCEAN_MAIN_TASK_SKIP_CHECKED = RuleImage(roi_front=(506,978,32,31), roi_back=(506,978,32,31), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/memory_ocean/memory_ocean_main_task_skip_checked.png")
	# 忆海心阶真我之境弹窗开始挑战按钮 
	I_MEMORY_OCEAN_MAIN_TASK_START_BUTTON = RuleImage(roi_front=(271,961,180,60), roi_back=(271,961,180,60), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/memory_ocean/memory_ocean_main_task_start_button.png")
	# 忆海心阶真我之境打开图标 
	I_MEMORY_OCEAN_MAIN_TASK = RuleImage(roi_front=(403,604,88,89), roi_back=(403,604,88,89), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/memory_ocean/memory_ocean_main_task.png")
	# 忆海心阶境遇弹窗页面标题 
	I_MEMORY_OCEAN_SUB_TASK_PAGE = RuleImage(roi_front=(65,344,139,51), roi_back=(56,261,249,51), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/memory_ocean/memory_ocean_sub_task_page.png")
	# 忆海心阶境遇弹窗开始挑战按钮 
	I_MEMORY_OCEAN_SUB_TASK_START_BUTTON = RuleImage(roi_front=(466,875,173,60), roi_back=(466,875,173,60), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/memory_ocean/memory_ocean_sub_task_start_button.png")


	# Ocr Rule Assets
	# 境遇挑战已获得 
	O_MEMORY_OCEAN_SUB_TASK_OBTAINED = RuleOcr(roi=(296,571,67,22), area=(296,571,67,22), mode="Single", method="Default", keyword="已获得", name="memory_ocean_sub_task_obtained")


	# Click Rule Assets
	# 美甲入口点击区域 
	C_NAIL_ART_ENTRANCE = RuleClick(roi_front=(83,1061,261,113), roi_back=(83,1061,261,113), name="nail_art_entrance")
	# 美甲-前往采购入口点击区域 
	C_NAIL_ART_PURCHASE_ENTRANCE = RuleClick(roi_front=(242,385,110,84), roi_back=(242,385,110,84), name="nail_art_purchase_entrance")
	# 美甲-前往采购-设计专区点击区域 
	C_NAIL_ART_PURCHASE_DESIGN_ZONE = RuleClick(roi_front=(18,164,146,37), roi_back=(18,164,146,37), name="nail_art_purchase_design_zone")
	# 美甲-前往采购-设计专区-免费缤纷星券点击区域 
	C_NAIL_ART_PURCHASE_DESIGN_ZONE_FREE = RuleClick(roi_front=(530,280,141,51), roi_back=(530,280,141,51), name="nail_art_purchase_design_zone_free")
	# 美甲-前往采购-设计专区-每周星券add区域 
	C_NAIL_ART_PURCHASE_DESIGN_ZONE_ADD_BUTTON = RuleClick(roi_front=(514,736,31,28), roi_back=(514,736,31,28), name="nail_art_purchase_design_zone_add_button")
	# 美甲-我的店铺-无效点击区域 
	C_NAIL_ART_SHOP_INVALID_AREA = RuleClick(roi_front=(83,165,379,122), roi_back=(83,165,379,122), name="nail_art_shop_invalid_area")


	# Image Rule Assets
	# 美甲前往采购的提示按钮 
	I_NAIL_ART_PURCHASE_TIP = RuleImage(roi_front=(331,355,20,24), roi_back=(331,355,20,24), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nail_art/nail_art_purchase_tip.png")
	# 美甲前往采购的页面 
	I_NAIL_ART_PURCHASE_PAGE = RuleImage(roi_front=(545,51,159,95), roi_back=(545,51,159,95), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nail_art/nail_art_purchase_page.png")
	# 美甲-前往采购-设计专区的页面 
	I_NAIL_ART_PURCHASE_DESIGN_ZONE_PAGE = RuleImage(roi_front=(104,273,49,53), roi_back=(104,273,49,53), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nail_art/nail_art_purchase_design_zone_page.png")
	# 美甲-前往采购-设计专区-获取星券提示图 
	I_NAIL_ART_PURCHASE_DESIGN_ZONE_GET_TICKET = RuleImage(roi_front=(332,566,64,81), roi_back=(332,566,64,81), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nail_art/nail_art_purchase_design_zone_get_ticket.png")
	# 美甲-前往采购-设计专区-每周星券兑换图 
	I_NAIL_ART_PURCHASE_DESIGN_ZONE_WEEK_TICKET = RuleImage(roi_front=(99,413,65,152), roi_back=(99,413,65,152), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nail_art/nail_art_purchase_design_zone_week_ticket.png")
	# 美甲-前往采购-设计专区-每周星券兑换按钮 
	I_NAIL_ART_PURCHASE_DESIGN_ZONE_WEEK_BUTTON = RuleImage(roi_front=(530,539,139,46), roi_back=(530,539,139,46), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nail_art/nail_art_purchase_design_zone_week_button.png")
	# 美甲-前往采购-设计专区-每周星券弹窗兑换按钮区域 
	I_NAIL_ART_PURCHASE_DESIGN_ZONE_WEEK_EXCHANGE = RuleImage(roi_front=(159,804,405,55), roi_back=(159,804,405,55), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nail_art/nail_art_purchase_design_zone_week_exchange.png")
	# 美甲-我的店铺入口 
	I_NAIL_ART_SHOP_ENTRANCE = RuleImage(roi_front=(60,1062,120,110), roi_back=(60,1062,120,110), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nail_art/nail_art_shop_entrance.png")
	# 美甲-我的店铺-雇佣店员按钮 
	I_NAIL_ART_SHOP_EMPLOYMENT_BUTTON = RuleImage(roi_front=(132,660,192,51), roi_back=(132,660,192,51), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nail_art/nail_art_shop_employment_button.png")
	# 美甲-我的店铺-雇佣海蜇按钮 
	I_NAIL_ART_SHOP_EMPLOYMENT_PERSON = RuleImage(roi_front=(420,833,182,54), roi_back=(420,833,182,54), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nail_art/nail_art_shop_employment_person.png")
	# 美甲-我的店铺-特约顾客图标 
	I_NAIL_ART_SHOP_SPECIAL = RuleImage(roi_front=(48,884,84,71), roi_back=(48,884,84,71), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nail_art/nail_art_shop_special.png")
	# 美甲-我的店铺-周好评礼包图标 
	I_NAIL_ART_SHOP_PACKAGE = RuleImage(roi_front=(46,1152,91,71), roi_back=(46,1152,91,71), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nail_art/nail_art_shop_package.png")
	# 美甲-我的店铺-周好评奖励弹窗标题 
	I_NAIL_ART_SHOP_PACKAGE_BOARD = RuleImage(roi_front=(289,219,145,33), roi_back=(289,219,145,33), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nail_art/nail_art_shop_package_board.png")
	# 美甲-我的店铺-提取心意币按钮 
	I_NAIL_ART_SHOP_EXTRACT_BUTTON = RuleImage(roi_front=(501,1155,149,42), roi_back=(501,1155,149,42), threshold=0.9, method="Template matching", file="./tasks/Nikki_daily/nail_art/nail_art_shop_extract_button.png")


	# Ocr Rule Assets
	# 美甲入口文本 
	O_NAIL_ART_ENTRANCE_TEXT = RuleOcr(roi=(95,1061,64,35), area=(95,1061,64,35), mode="Single", method="Default", keyword="美甲", name="nail_art_entrance_text")
	# 美甲页标题 
	O_NAIL_ART_PAGE = RuleOcr(roi=(393,27,304,64), area=(393,27,304,64), mode="Single", method="Default", keyword="美甲工作间", name="nail_art_page")
	# 可兑换数量 
	O_NAIL_ART_EXCHANGE_COUNT = RuleOcr(roi=(227,738,42,23), area=(227,738,42,23), mode="DigitCounter", method="Default", keyword="", name="nail_art_exchange_count")
	# 兑换数量 
	O_NAIL_ART_EXCHANGE_NUM = RuleOcr(roi=(452,735,23,29), area=(452,735,23,29), mode="Digit", method="Default", keyword="", name="nail_art_exchange_num")
	# 周奖励领取按钮 
	O_NAIL_ART_SHOP_PACKAGE_RECEIVE_1 = RuleOcr(roi=(512,471,124,43), area=(512,471,124,43), mode="Single", method="Default", keyword="", name="nail_art_shop_package_receive_1")
	# 周奖励领取按钮 
	O_NAIL_ART_SHOP_PACKAGE_RECEIVE_2 = RuleOcr(roi=(512,535,124,43), area=(512,535,124,43), mode="Single", method="Default", keyword="", name="nail_art_shop_package_receive_2")
	# 周奖励领取按钮 
	O_NAIL_ART_SHOP_PACKAGE_RECEIVE_3 = RuleOcr(roi=(512,708,124,43), area=(512,708,124,43), mode="Single", method="Default", keyword="", name="nail_art_shop_package_receive_3")
	# 周奖励领取按钮 
	O_NAIL_ART_SHOP_PACKAGE_RECEIVE_4 = RuleOcr(roi=(512,881,124,43), area=(512,881,124,43), mode="Single", method="Default", keyword="", name="nail_art_shop_package_receive_4")


	# Swipe Rule Assets
	# 向上滑动弹窗内容 
	S_NAIL_ART_SHOP_PACKAGE_SWIPE = RuleSwipe(roi_front=(118,856,366,131), roi_back=(118,224,366,131), mode="default", name="nail_art_shop_package_swipe")


	# Click Rule Assets
	# 设计中心入口点击区域 
	C_DESIGN_CENTER_ENTRANCE = RuleClick(roi_front=(46,1139,77,90), roi_back=(46,1139,77,90), name="design_center_entrance")
	# 开始旅程入口点击区域 
	C_START_JOURNEY_ENTRANCE = RuleClick(roi_front=(275,1139,77,90), roi_back=(275,1139,77,90), name="start_journey_entrance")
	# 搭配页面的跳过战斗点击区域 
	C_COLLOCATION_PROCESS_SKIP_AREA = RuleClick(roi_front=(58,1113,27,24), roi_back=(58,1113,27,24), name="collocation_process_skip_area")


	# Image Rule Assets
	# 分享按钮 
	I_SHARE_BUTTON = RuleImage(roi_front=(633,1176,54,50), roi_back=(633,1176,54,50), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/share_button.png")
	# 退出按钮 
	I_EXIT_BUTTON = RuleImage(roi_front=(5,36,76,64), roi_back=(5,36,76,64), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/exit_button.png")
	# 退出按钮(稍微偏下) 
	I_EXIT_BUTTON_2 = RuleImage(roi_front=(5,45,76,64), roi_back=(5,45,76,64), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/exit_button.png")
	# 退出按钮(稍微偏下++) 
	I_EXIT_BUTTON_3 = RuleImage(roi_front=(5,55,76,64), roi_back=(5,55,76,64), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/exit_button.png")
	# 退出按钮(稍微偏上) 
	I_EXIT_BUTTON_4 = RuleImage(roi_front=(5,17,76,64), roi_back=(5,17,76,64), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/exit_button.png")
	# 获取途径弹窗页面标题 
	I_GET_WAY_PAGE = RuleImage(roi_front=(297,271,130,48), roi_back=(297,271,130,48), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/get_way_page.png")
	# 获取途径弹窗页面的前往按钮 
	I_GET_WAY_PROCEED_BUTTON = RuleImage(roi_front=(490,588,121,48), roi_back=(490,588,121,48), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/get_way_proceed_button.png")
	# 获取途径弹窗页面的前往按钮 
	I_GET_WAY_PROCEED_BUTTON_2 = RuleImage(roi_front=(490,563,121,48), roi_back=(490,563,121,48), threshold=0.7, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/get_way_proceed_button.png")
	# 调查行动弹窗页面 
	I_GET_WAY_PROCEED_SURVEY_PAGE = RuleImage(roi_front=(268,267,190,55), roi_back=(268,267,190,55), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/get_way_proceed_survey_page.png")
	# 开始故事按钮 
	I_GET_WAY_PROCEED_START_BUTTON_1 = RuleImage(roi_front=(489,898,153,48), roi_back=(489,898,153,48), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/get_way_proceed_start_button.png")
	# 开始故事按钮 
	I_GET_WAY_PROCEED_START_BUTTON_2 = RuleImage(roi_front=(489,820,153,48), roi_back=(489,820,153,48), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/get_way_proceed_start_button.png")
	# 开始故事按钮 
	I_GET_WAY_PROCEED_START_BUTTON_3 = RuleImage(roi_front=(503,701,125,37), roi_back=(503,701,125,37), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/get_way_proceed_start_button_survey.png")
	# 开始故事按钮 
	I_GET_WAY_PROCEED_START_BUTTON_4 = RuleImage(roi_front=(489,842,153,48), roi_back=(489,842,153,48), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/get_way_proceed_start_button.png")
	# 挑战多次按钮 
	I_GET_WAY_PROCEED_CHALLENGE_1 = RuleImage(roi_front=(220,895,116,45), roi_back=(220,895,116,45), threshold=0.7, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/get_way_proceed_challenge.png")
	# 挑战多次按钮 
	I_GET_WAY_PROCEED_CHALLENGE_2 = RuleImage(roi_front=(220,815,116,45), roi_back=(220,815,116,45), threshold=0.7, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/get_way_proceed_challenge.png")
	# 挑战多次按钮 
	I_GET_WAY_PROCEED_CHALLENGE_3 = RuleImage(roi_front=(507,829,116,45), roi_back=(507,829,116,45), threshold=0.7, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/get_way_proceed_challenge_2.png")
	# 挑战多次按钮 
	I_GET_WAY_PROCEED_CHALLENGE_4 = RuleImage(roi_front=(220,840,116,45), roi_back=(220,840,116,45), threshold=0.7, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/get_way_proceed_challenge.png")
	# 搭配页面的推荐搭配按钮 
	I_COLLOCATION_PROCESS_RECOMMEND_BUTTON = RuleImage(roi_front=(584,1181,133,45), roi_back=(584,1181,133,45), threshold=0.7, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/collocation_process_recommend_button.png")
	# 搭配页面的下一步按钮 
	I_COLLOCATION_PROCESS_NEXT_BUTTON = RuleImage(roi_front=(53,1177,188,54), roi_back=(53,1177,188,54), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/collocation_process_next_button.png")
	# 搭配页面的确认按钮 
	I_COLLOCATION_PROCESS_SURE_BUTTON = RuleImage(roi_front=(415,684,156,56), roi_back=(415,684,156,56), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/collocation_process_sure_button.png")
	# 搭配页面的装备印象按钮 
	I_COLLOCATION_PROCESS_EQUIP = RuleImage(roi_front=(541,385,133,45), roi_back=(541,385,133,45), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/collocation_process_equip.png")
	# 确定 
	I_COLLOCATION_PROCESS_SURE = RuleImage(roi_front=(275,1087,169,51), roi_back=(275,1087,169,51), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/collocation_process_sure.png")
	# 搭配页面的装备印象弹窗 
	I_COLLOCATION_PROCESS_EQUIP_PAGE = RuleImage(roi_front=(289,178,142,50), roi_back=(289,178,142,50), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/collocation_process_equip_page.png")
	# 搭配页面的装备印象一键穿戴 
	I_COLLOCATION_PROCESS_EQUIP_ONECLICK = RuleImage(roi_front=(476,1017,126,30), roi_back=(476,1017,126,30), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/collocation_process_equip_oneclick.png")
	# 搭配页面的装备印象确定 
	I_COLLOCATION_PROCESS_EQUIP_SURE = RuleImage(roi_front=(415,1075,173,58), roi_back=(415,1075,173,58), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/collocation_process_equip_sure.png")
	# 搭配页面的跳过战斗checked 
	I_COLLOCATION_PROCESS_SKIP_CHECKED = RuleImage(roi_front=(58,1113,27,24), roi_back=(58,1113,27,24), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/nikki_daily/collocation_process_skip_checked.png")


	# Ocr Rule Assets
	# 主页设计中心文本 
	O_DESIGN_CENTER_ENTRANCE_TEXT = RuleOcr(roi=(44,1206,79,22), area=(44,1206,79,22), mode="Single", method="Default", keyword="设计中心", name="design_center_entrance_text")
	# 主页开始旅程文本 
	O_START_JOURNEY_ENTRANCE_TEXT = RuleOcr(roi=(273,1206,79,22), area=(273,1206,79,22), mode="Single", method="Default", keyword="开始旅程", name="start_journey_entrance_text")
	# 提示文本位置 
	O_TIP_TEXT = RuleOcr(roi=(222,623,278,36), area=(222,623,278,36), mode="Single", method="Default", keyword="", name="tip_text")
	# 体力数据 
	O_POWER_COUNT = RuleOcr(roi=(129,10,86,22), area=(129,10,86,22), mode="DigitCounter", method="Default", keyword="", name="power_count")


	# Swipe Rule Assets
	# 调查行动向上滑动内容 
	S_GET_WAY_PROCEED_SURVEY_SWIPE = RuleSwipe(roi_front=(167,893,250,72), roi_back=(167,300,250,72), mode="default", name="get_way_proceed_survey_swipe")


	# Click Rule Assets
	# 点击无效区域 
	C_RECEIVE_MAIL_INVALID_AREA = RuleClick(roi_front=(212,96,199,90), roi_back=(212,96,199,90), name="receive_mail_invalid_area")


	# Image Rule Assets
	# 邮件主页入口图标 
	I_RECEIVE_MAIL_ENTRANCE = RuleImage(roi_front=(657,373,38,42), roi_back=(657,373,38,42), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/receive_mail/receive_mail_entrance.png")
	# 邮件弹窗 
	I_RECEIVE_MAIL_PAGE = RuleImage(roi_front=(288,252,145,48), roi_back=(288,252,145,48), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/receive_mail/receive_mail_page.png")
	# 全部领取按钮 
	I_RECEIVE_MAIL_ALL_RECEIVE = RuleImage(roi_front=(421,953,162,55), roi_back=(421,953,162,55), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/receive_mail/receive_mail_all_receive.png")


	# Click Rule Assets
	# 商场充值tab点击区域 
	C_SHOP_TASK_VIP_TAB_AREA = RuleClick(roi_front=(609,129,72,65), roi_back=(609,129,72,65), name="shop_task_vip_tab_area")
	# 商场充值尊享点击区域 
	C_SHOP_TASK_VIP_BUTTON = RuleClick(roi_front=(59,524,595,103), roi_back=(59,524,595,103), name="shop_task_vip_button")


	# Image Rule Assets
	# 商城主页入口图标 
	I_SHOP_TASK_ENTRANCE = RuleImage(roi_front=(652,738,40,38), roi_back=(652,738,40,38), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/shop_task/shop_task_entrance.png")
	# 商城主页 
	I_SHOP_TASK_PAGE = RuleImage(roi_front=(302,48,115,49), roi_back=(302,48,115,49), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/shop_task/shop_task_page.png")
	# 商城_材料专区tab_未选中 
	I_SHOP_TASK_STUFF_1 = RuleImage(roi_front=(355,436,122,41), roi_back=(355,436,122,41), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/shop_task/shop_task_stuff.png")
	# 商城_材料专区tab_未选中 
	I_SHOP_TASK_STUFF_2 = RuleImage(roi_front=(523,436,122,41), roi_back=(523,436,122,41), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/shop_task/shop_task_stuff.png")
	# 商城_材料专区tab_选中 
	I_SHOP_TASK_STUFF_CHECKED_1 = RuleImage(roi_front=(355,436,122,41), roi_back=(355,436,122,41), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/shop_task/shop_task_stuff_checked.png")
	# 商城_材料专区tab_选中 
	I_SHOP_TASK_STUFF_CHECKED_2 = RuleImage(roi_front=(523,436,122,41), roi_back=(523,436,122,41), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/shop_task/shop_task_stuff_checked.png")
	# 商城_材料专区_周试剂免费按钮 
	I_SHOP_TASK_WEEK_FREE_BUTTON_1 = RuleImage(roi_front=(54,788,126,39), roi_back=(54,788,126,39), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/shop_task/shop_task_week_free_button.png")
	# 商城_材料专区_周试剂免费按钮 
	I_SHOP_TASK_WEEK_FREE_BUTTON_2 = RuleImage(roi_front=(54,788,126,39), roi_back=(54,788,126,39), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/shop_task/shop_task_week_free_receive.png")
	# 商城_材料专区_周试剂免费按钮 
	I_SHOP_TASK_WEEK_FREE_BUTTON_3 = RuleImage(roi_front=(54,788,126,39), roi_back=(54,788,126,39), threshold=0.95, method="Template matching", file="./tasks/Nikki_daily/shop_task/shop_task_week_free_receive_2.png")
	# 商城_材料专区_周试剂免费购买按钮 
	I_SHOP_TASK_WEEK_FREE_BUY = RuleImage(roi_front=(161,974,402,58), roi_back=(161,974,402,58), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/shop_task/shop_task_week_free_buy.png")
	# 商城_充值tab右上角是否有提示领取 
	I_SHOP_TASK_VIP_TIP = RuleImage(roi_front=(673,122,11,10), roi_back=(673,122,11,10), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/shop_task/shop_task_vip_tip.png")
	# 商城充值页面的提示信息 
	I_SHOP_TASK_VIP_TEXT = RuleImage(roi_front=(118,457,461,28), roi_back=(118,457,461,28), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/shop_task/shop_task_vip_text.png")
	# 商城尊享福利每周礼包 
	I_SHOP_TASK_VIP_WEEK_PACKAGE = RuleImage(roi_front=(562,148,78,100), roi_back=(562,148,78,100), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/shop_task/shop_task_vip_week_package.png")


	# Click Rule Assets
	# 联盟任务机密执行多次按钮区域 
	C_UNION_TASK_MISSION_RUN_REPEAT = RuleClick(roi_front=(244,1160,119,48), roi_back=(244,1160,119,48), name="union_task_mission_run_repeat")
	# 联盟商店幻之券点击按钮 
	C_UNION_TASK_SHOP_EXCHANGE = RuleClick(roi_front=(542,651,139,37), roi_back=(542,651,139,37), name="union_task_shop_exchange")
	# 联盟商店幻之券max按钮 
	C_UNION_TASK_SHOP_MAX_BUTTON = RuleClick(roi_front=(510,662,35,24), roi_back=(510,662,35,24), name="union_task_shop_max_button")


	# Image Rule Assets
	# 联盟主页入口图标 
	I_UNION_TASK_ENTRANCE = RuleImage(roi_front=(655,277,38,42), roi_back=(655,277,38,42), threshold=0.4, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_entrance.png")
	# 联盟福利图标 
	I_UNION_TASK_WELFARE = RuleImage(roi_front=(43,1034,45,76), roi_back=(43,1034,45,76), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_welfare.png")
	# 联盟机密任务图标 
	I_UNION_TASK_MISSION = RuleImage(roi_front=(365,810,89,102), roi_back=(365,810,89,102), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_mission.png")
	# 联盟捐献图标 
	I_UNION_TASK_DONATE = RuleImage(roi_front=(551,813,89,102), roi_back=(551,813,89,102), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_donate.png")
	# 联盟商店图标 
	I_UNION_TASK_SHOP = RuleImage(roi_front=(551,629,89,102), roi_back=(551,629,89,102), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_shop.png")
	# 联盟福利弹窗标题 
	I_UNION_TASK_WELFARE_POP = RuleImage(roi_front=(300,251,122,38), roi_back=(300,251,122,38), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_welfare_pop.png")
	# 联盟福利一键领取按钮 
	I_UNION_TASK_WELFARE_RECEIVE = RuleImage(roi_front=(269,955,181,48), roi_back=(269,955,181,48), threshold=0.9, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_welfare_receive.png")
	# 联盟捐献弹窗标题 
	I_UNION_TASK_DONATE_POP = RuleImage(roi_front=(265,314,190,42), roi_back=(265,314,190,42), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_donate_pop.png")
	# 联盟捐献免费捐赠按钮 
	I_UNION_TASK_DONATE_FREE = RuleImage(roi_front=(95,801,126,56), roi_back=(95,801,126,56), threshold=0.9, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_donate_free.png")
	# 联盟捐献金币捐赠按钮 
	I_UNION_TASK_DONATE_GOLD = RuleImage(roi_front=(95,801,126,56), roi_back=(95,801,126,56), threshold=0.9, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_donate_gold.png")
	# 联盟机密任务页面标题 
	I_UNION_TASK_MISSION_PAGE = RuleImage(roi_front=(250,64,215,62), roi_back=(250,64,215,62), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_mission_page.png")
	# 联盟机密任务页面<前往当前目标>按钮 
	I_UNION_TASK_MISSION_GOTO_BUTTON = RuleImage(roi_front=(254,1156,211,52), roi_back=(254,1156,211,52), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_mission_goto_button.png")
	# 联盟机密任务执行一次按钮（仅一个按钮） 
	I_UNION_TASK_MISSION_RUN_ALONE = RuleImage(roi_front=(112,1159,121,48), roi_back=(112,1159,121,48), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_mission_run_alone.png")
	# 联盟商店页面标题 
	I_UNION_TASK_SHOP_PAGE = RuleImage(roi_front=(75,454,120,49), roi_back=(75,454,120,49), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_shop_page.png")
	# 联盟商店幻之券图标 
	I_UNION_TASK_SHOP_TICKET = RuleImage(roi_front=(409,609,68,43), roi_back=(409,609,68,43), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_shop_ticket.png")
	# 联盟商店幻之券购买按钮 
	I_UNION_TASK_SHOP_EXCHANGE_BUTTON = RuleImage(roi_front=(159,715,398,58), roi_back=(159,715,398,58), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/union_task/union_task_shop_exchange_button.png")


	# Ocr Rule Assets
	# 执行次数 
	O_UNION_TASK_MISSION_COUNT = RuleOcr(roi=(152,1240,39,24), area=(152,1240,39,24), mode="DigitCounter", method="Default", keyword="", name="union_task_mission_count")
	# 幻之券兑换数量 
	O_UNION_TASK_SHOP_COUNT = RuleOcr(roi=(636,615,36,25), area=(636,615,36,25), mode="DigitCounter", method="Default", keyword="", name="union_task_shop_count")
	# 幻之券兑换数 
	O_UNION_TASK_SHOP_NUM = RuleOcr(roi=(382,661,16,23), area=(382,661,16,23), mode="Digit", method="Default", keyword="", name="union_task_shop_num")


	# Click Rule Assets
	# 福利页面每日签到tab点击区域 
	C_WELFARE_TASK_SIGN_TAB_AREA = RuleClick(roi_front=(547,136,134,37), roi_back=(547,136,134,37), name="welfare_task_sign_tab_area")
	# 福利页面每日签到补签卡区域 
	C_WELFARE_TASK_RESIGN_AREA_1 = RuleClick(roi_front=(159,487,63,41), roi_back=(159,487,63,41), name="welfare_task_resign_area_1")
	# 福利页面每日签到补签卡区域 
	C_WELFARE_TASK_RESIGN_AREA_2 = RuleClick(roi_front=(270,487,63,41), roi_back=(270,487,63,41), name="welfare_task_resign_area_2")
	# 福利页面每日签到补签卡区域 
	C_WELFARE_TASK_RESIGN_AREA_3 = RuleClick(roi_front=(382,487,63,41), roi_back=(382,487,63,41), name="welfare_task_resign_area_3")
	# 福利页面每日签到补签卡区域 
	C_WELFARE_TASK_RESIGN_AREA_4 = RuleClick(roi_front=(495,487,63,41), roi_back=(495,487,63,41), name="welfare_task_resign_area_4")
	# 福利页面每日签到补签卡区域 
	C_WELFARE_TASK_RESIGN_AREA_5 = RuleClick(roi_front=(606,487,63,41), roi_back=(606,487,63,41), name="welfare_task_resign_area_5")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_1 = RuleClick(roi_front=(48,605,113,132), roi_back=(48,605,113,132), name="welfare_task_sign_area_1")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_2 = RuleClick(roi_front=(217,605,113,132), roi_back=(217,605,113,132), name="welfare_task_sign_area_2")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_3 = RuleClick(roi_front=(386,605,113,132), roi_back=(386,605,113,132), name="welfare_task_sign_area_3")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_4 = RuleClick(roi_front=(555,605,113,132), roi_back=(555,605,113,132), name="welfare_task_sign_area_4")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_5 = RuleClick(roi_front=(48,670,113,132), roi_back=(48,670,113,132), name="welfare_task_sign_area_5")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_6 = RuleClick(roi_front=(217,670,113,132), roi_back=(217,670,113,132), name="welfare_task_sign_area_6")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_7 = RuleClick(roi_front=(386,670,113,132), roi_back=(386,670,113,132), name="welfare_task_sign_area_7")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_8 = RuleClick(roi_front=(555,670,113,132), roi_back=(555,670,113,132), name="welfare_task_sign_area_8")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_9 = RuleClick(roi_front=(48,867,113,132), roi_back=(48,867,113,132), name="welfare_task_sign_area_9")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_10 = RuleClick(roi_front=(217,867,113,132), roi_back=(217,867,113,132), name="welfare_task_sign_area_10")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_11 = RuleClick(roi_front=(386,867,113,132), roi_back=(386,867,113,132), name="welfare_task_sign_area_11")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_12 = RuleClick(roi_front=(555,867,113,132), roi_back=(555,867,113,132), name="welfare_task_sign_area_12")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_13 = RuleClick(roi_front=(48,1061,113,132), roi_back=(48,1061,113,132), name="welfare_task_sign_area_13")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_14 = RuleClick(roi_front=(217,1061,113,132), roi_back=(217,1061,113,132), name="welfare_task_sign_area_14")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_15 = RuleClick(roi_front=(386,1061,113,132), roi_back=(386,1061,113,132), name="welfare_task_sign_area_15")
	# 福利页面每日签到可能的签到区域 
	C_WELFARE_TASK_SIGN_AREA_16 = RuleClick(roi_front=(555,1061,113,132), roi_back=(555,1061,113,132), name="welfare_task_sign_area_16")


	# Image Rule Assets
	# 福利主页入口图标 
	I_WELFARE_TASK_ENTRANCE = RuleImage(roi_front=(653,925,35,37), roi_back=(653,925,35,37), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/welfare_task/welfare_task_entrance.png")
	# 福利页面标题 
	I_WELFARE_TASK_PAGE = RuleImage(roi_front=(257,53,208,54), roi_back=(257,53,208,54), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/welfare_task/welfare_task_page.png")
	# 福利页面每日签到tab的提示 
	I_WELFARE_TASK_SIGN_TIP = RuleImage(roi_front=(691,135,7,8), roi_back=(691,135,7,8), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/welfare_task/welfare_task_sign_tip.png")
	# 福利页面每日签到tab选中状态 
	I_WELFARE_TASK_SIGN_TAB_CHECKED = RuleImage(roi_front=(547,136,134,37), roi_back=(547,136,134,37), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/welfare_task/welfare_task_sign_tab_checked.png")
	# 福利页面方舟补给tab未选中状态 
	I_WELFARE_TASK_SUPPLY_TAB_UNCHECKED = RuleImage(roi_front=(564,136,134,37), roi_back=(564,136,134,37), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/welfare_task/welfare_task_supply_tab_unchecked.png")
	# 福利页面方舟补给tab选中状态 
	I_WELFARE_TASK_SUPPLY_TAB_CHECKED = RuleImage(roi_front=(564,136,134,37), roi_back=(564,136,134,37), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/welfare_task/welfare_task_supply_tab_checked.png")
	# 福利页面方舟补给页面爱心图标 
	I_WELFARE_TASK_SUPPLY_HEART = RuleImage(roi_front=(529,454,58,31), roi_back=(529,454,58,31), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/welfare_task/welfare_task_supply_heart.png")
	# 福利页面方舟补给领取按钮 
	I_WELFARE_TASK_SUPPLY_RECEIVE_BUTTON_1 = RuleImage(roi_front=(481,580,161,61), roi_back=(481,580,161,61), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/welfare_task/welfare_task_supply_receive_button.png")
	# 福利页面方舟补给领取按钮 
	I_WELFARE_TASK_SUPPLY_RECEIVE_BUTTON_2 = RuleImage(roi_front=(481,893,161,61), roi_back=(481,893,161,61), threshold=0.8, method="Template matching", file="./tasks/Nikki_daily/welfare_task/welfare_task_supply_receive_button.png")


	# Swipe Rule Assets
	# 向左滑动tab内容 
	S_WELFARE_TASK_SWIPE = RuleSwipe(roi_front=(582,134,130,44), roi_back=(13,224,366,131), mode="default", name="welfare_task_swipe")


