from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class Nikki_restartAssets: 


	# Click Rule Assets
	# 关闭主页面公告按钮 
	C_CLOSE_POST_BTN = RuleClick(roi_front=(482,72,127,93), roi_back=(482,72,127,93), name="close_post_btn")


	# Image Rule Assets
	# 开始界面公告关闭 
	I_START_PAGE_POST = RuleImage(roi_front=(326,988,68,62), roi_back=(326,988,68,62), threshold=0.6, method="Template matching", file="./tasks/Nikki_restart/nikki_restart/start_page_post.png")
	# 主页信息栏爱心图标 
	I_MAIN_PAGE_POWER = RuleImage(roi_front=(129,13,20,18), roi_back=(129,13,20,18), threshold=0.4, method="Template matching", file="./tasks/Nikki_restart/nikki_restart/main_page_power.png")
	# 主页公告 
	I_MAIN_PAGE_POST = RuleImage(roi_front=(38,896,30,32), roi_back=(38,896,30,32), threshold=0.6, method="Template matching", file="./tasks/Nikki_restart/nikki_restart/main_page_post.png")
	# 更新确定按钮 
	I_UPDATE_VERIFY = RuleImage(roi_front=(376,694,196,56), roi_back=(376,694,196,56), threshold=0.8, method="Template matching", file="./tasks/Nikki_restart/nikki_restart/update_verify.png")
	# 年龄提示 
	I_AGE_REMIND = RuleImage(roi_front=(648,1196,60,62), roi_back=(648,1196,60,62), threshold=0.8, method="Template matching", file="./tasks/Nikki_restart/nikki_restart/age_remind.png")
	# 公告提示按钮未勾选 
	I_POST_UNCHECK = RuleImage(roi_front=(519,1022,32,27), roi_back=(519,1022,32,27), threshold=0.8, method="Template matching", file="./tasks/Nikki_restart/nikki_restart/post_uncheck.png")
	# 公告提示按钮勾选 
	I_POST_CHECK = RuleImage(roi_front=(519,1022,32,27), roi_back=(519,1022,32,27), threshold=0.8, method="Template matching", file="./tasks/Nikki_restart/nikki_restart/post_check.png")
	# 红包图标 
	I_RED_ENVELOPE = RuleImage(roi_front=(39,762,38,33), roi_back=(39,762,38,33), threshold=0.8, method="Template matching", file="./tasks/Nikki_restart/nikki_restart/red_envelope.png")


	# Ocr Rule Assets
	# 登录页点击开始进入游戏 
	O_LOGIN_ENTER_GAME = RuleOcr(roi=(243,1081,246,36), area=(243,1081,246,36), mode="Single", method="Default", keyword="点击开始", name="login_enter_game")
	# 主页公告提示文本 
	O_POST_TIPS = RuleOcr(roi=(568,1023,125,24), area=(568,1023,125,24), mode="Single", method="Default", keyword="今日不再提示", name="post_tips")


